// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportePublico.Data;

namespace TransportePublico.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211123020721_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TransportePublico.Models.Estacion", b =>
                {
                    b.Property<int>("IDEstacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreEstacion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IDEstacion");

                    b.ToTable("Estacion");
                });

            modelBuilder.Entity("TransportePublico.Models.Horario", b =>
                {
                    b.Property<int>("IDHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EstacionIDEstacion")
                        .HasColumnType("int");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDEstacion")
                        .HasColumnType("int");

                    b.Property<int>("IDRuta")
                        .HasColumnType("int");

                    b.Property<int?>("RutaIDRuta")
                        .HasColumnType("int");

                    b.HasKey("IDHorario");

                    b.HasIndex("EstacionIDEstacion");

                    b.HasIndex("RutaIDRuta");

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("TransportePublico.Models.Ruta", b =>
                {
                    b.Property<int>("IDRuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreRuta")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IDRuta");

                    b.ToTable("Ruta");
                });

            modelBuilder.Entity("TransportePublico.Models.Horario", b =>
                {
                    b.HasOne("TransportePublico.Models.Estacion", "Estacion")
                        .WithMany("Horarios")
                        .HasForeignKey("EstacionIDEstacion");

                    b.HasOne("TransportePublico.Models.Ruta", "Ruta")
                        .WithMany()
                        .HasForeignKey("RutaIDRuta");

                    b.Navigation("Estacion");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("TransportePublico.Models.Estacion", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
